version: '3'
volumes:
  sqldata:
networks:
  net:
services:
  sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:1.0.5
    volumes:
      - sqldata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
    ports:
      - 1333:1433
    networks:
      - net
  liquibase:
    image: liquibase/liquibase:4.7
    volumes:
      - ./:/liquibase/changelog/
    networks:
      - net
    depends_on:
      - sql-edge