--liquibase formatted sql

--changeset Amanda:1
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );
INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );
--rollback DELETE FROM CUSTOMERS WHERE ID=1;
--rollback DELETE FROM CUSTOMERS WHERE ID=2;
--rollback DELETE FROM CUSTOMERS WHERE ID=3;
--rollback DELETE FROM CUSTOMERS WHERE ID=4;
--rollback DELETE FROM CUSTOMERS WHERE ID=5;
--rollback DELETE FROM CUSTOMERS WHERE ID=6;